### ISSUE TITLE
UX for sharing individual projects could be improved

### ISSUE THREAD

**Issue by afraser** [HackBeanpot/build4blm#62]
As a visitor who would like to share a project with someone else, it isn't clear to me how to get a permalink to the project. And even if I do (by clicking "work on this project"), the `projects/:id` route isn't structured in a way that a first-time-visitor would know what they're seeing.

I would recommend one of two approaches:

1. Move the existing `projects/:id` route to `projects/:id/contact` (or similar), then point the `projects/:id` route at the view that renders details for a specific project in the open projects page.

2. Change the "Work on this project" CTA to say "View this project". Restructure the `projects/:id` page to be more of a project landing page. Move all the content from step 2 ("Review Project Details") to the top of the page (above the current h1... add a new H1 to the top with the project title.) Leave the remaining 3 steps under a second H1 at the lower part of the page.

I'd be happy to take on either of these tasks and open a PR. I'd just need to get set up with Airtable.

**Comment by feliciazhang** [comment]
We've updated the project urls, thanks for the suggestions!
